# Generated by Django 4.0.1 on 2022-01-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRCODE',
        ),
    ]
